name: Run Bash Script

on:
  workflow_dispatch:   # Actions tab-এ Run workflow বাটন দেখাবে
  push:
    branches: [ "main" ]

jobs:
  run-bash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ytdownloader.sh

      - name: Run script
        run: ./zphisher.sh
